### PR TITLE
native: add IsBigEndian bool const

### PR DESCRIPTION
**Pull request by bradfitz**
Per https://github.com/golang/go/issues/57237#issuecomment-1347539315

Updates golang/go#57237

### CODE REVIEW

**Comment by bradfitz** [comment]
cc @mdlayher

**Review by mdlayher — APPROVED** [review]
LGTM!

**Review by josharian — APPROVED** [review]
LGTM, thanks!

**Comment by mdlayher** [comment]
As a FYI, I have tagged v1.1.0 for Go module purposes.

**Pull request merged**
